### ISSUE TITLE
Uncaught TypeError if given invalid html string. Better error message?

### ISSUE THREAD

**Issue by raibima** [pveyes/htmr#13]
How to repro:
```js
// invalid html string
const input = '<a href="google.com></a>'

const htmr = require('htmr')(input)
```

```
TypeError: Cannot read property 'tag' of undefined
    at transform (/home/raibima.putra/node_modules/htmr/lib/index.js:105:18)
    at /home/raibima.putra/node_modules/htmr/lib/index.js:132:12
    at Array.map (<anonymous>)
    at convertServer (/home/raibima.putra/node_modules/htmr/lib/index.js:131:24)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
```

I spent hours trying to figure out what went wrong. It would have been easier if the error message was a little bit more descriptive.

FYI:
```js
// invalid html string
const input = '<a href="google.com></a>'

const parse = require('posthtml-parser')
parse(input)
```
will output
```
[ undefined ]
```

**Comment by pveyes** [comment]
Do you have any proposal what kind of error message would be helpful?

Is `Invalid html node <a href="google.com></a>` enough?

**Comment by raibima** [comment]
I think that would suffice :+1:

**Comment by anztrax** [comment]
yah i think that suffice too

**Comment by pveyes** [comment]
Turns out this is quite difficult problem, because detecting `undefined` in AST parse result can results in false positive.

Another problem is consistency. In browser, its HTML parser will forgive parse error and construct correct tree instead. Having different behaviour for server and browser is quite unacceptable.

For now I'm closing this issue. If in the future such method is found without sacrificing bundle size and consistency, we'll fix it.
