### ISSUE TITLE
Removal of whitespace-only text nodes

### ISSUE THREAD

**Issue by dmfrancisco** [pveyes/htmr#22]
Thank you for creating and maintaining this useful library 🙌 

I noticed that whitespace was not being preserved between tags. After reading the code I realize that this is on purpose and done by this code (in the browser version):

```js
else if (node.nodeType === NodeTypes.TEXT) {
  return node.textContent.trim() === '' ? null : unescape(node.textContent);
}
```

Personally I found this unexpected. For example:

```js
convert("<span>hello</span> <span>world!</span>")
```

Renders to:

> helloworld!

But I was expecting:

> hello world!

Another example I noticed on a code block that had been syntax highlighted:

```js
convert("<pre><span>Hello</span>\n<span>World</span></pre>")
```

Renders to:

<pre><span>Hello</span><span>World</span></pre>

But I was expecting:

<pre><span>Hello</span>
<span>World</span></pre>

For my application I created [a fork](https://github.com/listcommunity/htmr) where I'm simply not trimming the whitespace. Let me know if you agree with the expectations and think this behavior should change. Thanks again 👍

**Comment by pveyes** [comment]
You're right, I forgot the exact reason why I decided to trim the whitespace for text nodes but I think it make sense to not remove it. Now that you bring it up I think I'll add pre-processing for text node (so we can still trim before rendering)

Would you create PR for this changes? I've seen your fork but I'd suggest some changes in the test: remove the whitespace caused by template literal for existing test (so the existing snapshot doesn't need to change)
